Fix build-push auto-update test
This test has been failing recently with the error:

```
************************************************
realpath: ./build-push/test.sh: No such file or directory
realpath: missing operand
Try 'realpath --help' for more information.
ERROR: Fail.  Expecting match to
'Must.be.called.with.exactly.two.arguments' or
'does.not.appear.to.be.the.root.of.a.git.repo', got:
Auto-updating build-push operational scripts...
Obtaining latest version...
Installing...
/tmp/tmp-build-push-test-LpQS
Re-executing main.sh ...
```

Attempt to fix this by running the mock `main.sh` script using it's full
path and a completely clean shell environment.  Also, ensure install
script fully imports the automation common lib, and not just the
location & path variables.

Signed-off-by: Chris Evich <cevich@redhat.com>