Fix error caused by multi-line $AWSINI contents
This is somehow causing a silent failure of the workflow, with an error
coming from podman:

```
Error: error parsing env file "/tmp/env_file_<BLAH>": name "output "
has white spaces, poorly formatted name
```

This is due to the $AWSINI contents being mult-line.  Fix this by
making github-actions set the secret env. vars.  Then after making
sure they're exported, let podman figure out how to handle their
contents.

Also, split the data collection from data processing tasks to improve
debug-ability.  Rename the output file and artifact to indicate their
expected contents better.

Signed-off-by: Chris Evich <cevich@redhat.com>